---
version: '2.0'
services:
  #iperf3:
  #  build: ./iperf3_server/
  #  ports:
  #      - "5201:5201"
  #  image: mlabbe/iperf3
  iperf3:
    image: mlabbe/iperf3
    build: .
    ports:
        - "5201:5201"

  nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager
    build: .
    ports:
      - "8181:8181"
      - "8080:8080"
      - "4443:4443"
    volumes:
      - "/mnt/mobius/Backup/dev/nginx-proxy-manager:/config:rw"
