---
version: '3.8'
services:
  
  iperf3:
    image: mlabbe/iperf3
    build: .
    ports:
        - "5201:5201"

  nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager
    build: .
    ports:
      - "81:8181"
      - "80:8080"
      - "443:4443"
    volumes:
      - type: bind
        source: /mnt/mobius/Backup/docker/dev/nginx-proxy-manager
        target: /config
