---
version: '2.4'
services:
  pb:
    build:
      context: .
    ports:
      - '10002:10002'
    volumes:
      - /mnt/mobius/Backup/docker/dev/pb:/pb
    environment:
      - 'LISTEN_ADDRESS=::'
      - 'LISTEN_PORT=10002'
      - 'CDN_PREFIX=//d34zelngniy2d8.cloudfront.net'

  mongodb:
    image: mongo:latest
