---
version: '2.4'
services:
  
  ytdl_material:
    environment: 
        ALLOW_CONFIG_MUTATIONS: 'true'
    restart: always
    volumes:
        - /mnt/mobius/Backup/docker/dev/youtube-dl/appdata:/app/appdata
        - /mnt/mobius/staging/youtube-dl/audio:/app/audio
        - /mnt/mobius/staging/youtube-dl/video:/app/video
        - /mnt/mobius/Backup/docker/dev/youtube-dl/subscriptions:/app/subscriptions
    ports:
        - "8998:17442"
    image: tzahi12345/youtubedl-material:latest          
