---
version: '3'
services:
  whoogle-search:
    image: benbusby/whoogle-search
    container_name: whoogle-search
    ports:
      - 5000:5000
    restart: unless-stopped
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]