---
version: '3'
services:
  ombi:
    image: linuxserver/ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/mobius/docker/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]