---
version: "2.4"
services:
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/mobius/docker/ombi/config:/config:rw
    ports:
      - 3579:3579
    restart: unless-stopped
