---
version: "2.4"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
      - "67:67/udp"
      - "8088:80/tcp"
      - "8443:443/tcp"
    environment:
      TZ: "America/New-York"
      WEBPASSWORD: 'password'
    volumes:
      - "/mnt/mobius/docker/pihole/etc/:/etc/"
      - "/mnt/mobius/docker/pihole/var/:/var/log/"
    dns:
      - 192.168.12.1
    restart: unless-stopped
