---
version: "3"
services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - PASSWORD=Uid5N5iAGloDFoAzsZZE5UGGcXtDhT5r1Tcm7YgC
      - SUDO_PASSWORD=Uid5N5iAGloDFoAzsZZE5UGGcXtDhT5r1Tcm7YgC
    volumes:
      - /mnt/mobius/docker/code/config:/config:Z
    ports:
      - 9443:8443
    restart: unless-stopped
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
