---
version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/mobius/docker/heimdall/config:/config
    ports:
      - 10080:80
      - 10443:443
    restart: unless-stopped
