---
version: '3'
services:
  guacamole:
    image: oznu/guacamole
    container_name: guacamole
    volumes:
      - /mnt/mobius/docker/guacamole/config:/config
      - /mnt/mobius/docker/guacamole/etc_guacamole:/etc/guacamole
    ports:
      - 8081:8080
    restart:  unless-stopped
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
