version: "2"
services:
  guacamole:
    image: oznu/guacamole
    container_name: guacamole
    volumes:
      - /mnt/mobius/docker/guacamole/config:/config
    ports:
      - 8081:8080
    environment:
      - GUACAMOLE_HOME=/mnt/mobius/docker/guacamole/config/guacamole
      # - EXTENSIONS=auth-totp
    restart:  unless-stopped
