# guacamole docker compose (swarm)
---
# this comment is a hack
version: '3'
services:
  guacamole:
    image: oznu/guacamole
    container_name: guacamole
    volumes:
      - /mnt/gluster/guacamole/config:/config
      - /mnt/mobius/docker/guacamole/etc_guacamole:/etc/guacamole
    ports:
      - 8081:8080
    restart:  unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
