---
version: 2
services:
  handbrake:
    image: jlesage/handbrake
    ports:
      - "5800:5800"
    volumes:
      - /mnt/mobius/docker/handbrake:/config:rw
      - /mnt/mobius/staging/handbrake/storage:/storage:ro
      - /mnt/mobius/staging/handbrake/watch:/watch:rw
      - /mnt/mobius/staging/handbrake/output:/output:rw
    restart: unless-stopped
