---
# this comment is a hack
version: '3'
services:
  handbrake:
    image: jlesage/handbrake
    ports:
      - "5800:5800"
    volumes:
      - /mnt/gluster/handbrake:/config:rw
      - /mnt/gluster/handbrake/storage:/storage:ro
      - /mnt/gluster/handbrake/watch:/watch:rw
      - /mnt/gluster/handbrake/output:/output:rw
    restart: unless-stopped
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
