## Configuration

---
title: "Grand Ol' Dungeon of the Horned God"
subtitle: "Homer"
# documentTitle: "Welcome" # Customize the browser tab text
logo: "assets/icons/icon-maskable.png"
# Alternatively a fa icon can be provided:
# icon: "fas fa-skull-crossbones"

header: true # Set to false to hide the header
footer: false # set false if you want to hide it.

columns: "auto" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example)

# Optional theming
theme: default # 'default' or one of the themes available in 'src/assets/themes'.

#default colors from github:
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
    background-image: "assets/your/light/bg.png"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"
    background-image: "assets/your/dark/bg.png"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/educatedCaveman"
    target: "_blank" # optional html tag target attribute
  - name: "Font Awesome Icons"
    icon: "fab fa-font-awesome"
    url:  "https://fontawesome.com/v4.7.0/icons/"

services:
  - name: "Servers"
    icon: "fas fa-server"
    items:
      - name: "Mobius"
        icon: "fas fa-server"
        subtitle: "TrueNAS Server"
        tag:  "Server"
        url:  "https://mobius.drak3.io"

      - name: "Tesseract"
        icon: "fas fa-server"
        subtitle: "TrueNAS Server"
        tag:  "Server"
        url:  "https://tesseract.drak3.io"

      - name: "Unifi Controller"
        icon: "fas fa-server"
        subtitle: "Unifi Controller"
        tag:  "Server"
        url:  "https://unifi.drak3.io"

  - name: "iDRAC / IPMI"
    icon: "fas fa-server"
    items:
      - name: "Mobius (iDRAC)"
        icon: "fas fa-server"
        subtitle: "Mobius (iDRAC)"
        tag:  "admin"
        url:  "https://idrac.mobius.drak3.io"

      - name: "Tesseract (iDRAC)"
        icon: "fas fa-server"
        subtitle: "Tesseract (iDRAC)"
        tag:  "admin"
        url:  "https://idrac.tesseract.drak3.io"

      - name: "pfSense (IPMI)"
        icon: "fas fa-server"
        subtitle: "pfSense (IPMI)"
        tag:  "admin"
        url:  "http://192.168.1.10"

  - name: "Services"
    icon: "fas fa-server"
    items:

      - name: "Jenkins"
        logo: "assets/jenkins.svg"
        subtitle: "jenkins.vm"
        tag:  "Services"
        url:  "https://jenkins.drak3.io/"

      - name: "Portainer (PRD)"
        logo: "assets/docker.png"
        subtitle: "portainer.drak3.io"
        tag:  "Services"
        url:  "https://portainer.drak3.io/"

      - name: "Portainer (DEV)"
        logo: "assets/docker.png"
        subtitle: "portainer.dev.drak3.io"
        tag:  "Services"
        url:  "https://portainer.dev.drak3.io/"

      - name: "qBittorrent"
        logo: "assets/qbittorrent.png"
        subtitle: "qbittorrent.vm"
        tag:  "Services"
        url:  "https://qbt.drak3.io/"

      - name: "Syncthing"
        logo: "assets/syncthing.png"
        subtitle: "syncthing.vm"
        tag:  "Services"
        url:  "https://sync.drak3.io/syncthing/"

      - name: "Gitea"
        logo: "assets/Gitea_Logo.svg"
        subtitle: "Gitea"
        tag:  "Services"
        url:  "https://git.drak3.io/"

  - name: "Pi-Hole"
    logo: "assets/pi_hole_icon_BW.svg"
    items:

      - name: "Singularity"
        logo: "assets/Pi-hole_vector_logo.svg.png"
        subtitle: "singularity.vm"
        tag:  "pihole"
        url:  "https://pihole.drak3.io/admin/index.php"

      - name: "Event Horizon"
        logo: "assets/Pi-hole_vector_logo.svg.png"
        subtitle: "event-horizon.srv"
        tag:  "pihole"
        url:  "https://pihole2.drak3.io/admin/index.php"

      - name: "Pi-Hole (docker)"
        logo: "assets/Pi-hole_vector_logo.svg.png"
        subtitle: "tbd.drak3.io"
        tag:  "pihole"
        url:  "https://duckduckgo.com"

  - name: "Applications"
    icon: "fas fa-user"
    items:

      - name: "NextCloud"
        logo: "assets/Nextcloud_Logo.svg"
        subtitle: "nectcloud.vm"
        tag:  "application"
        url:  "https://cloud.drak3.io"

      - name: "Plex"
        logo: "assets/plex.svg"
        subtitle: "https://plex.drak3.io"
        tag:  "application"
        url:  "https://plex.drak3.io"

      - name: "YouTube DL"
        icon: "fab fa-youtube"
        subtitle: "https://ytdl.drak3.io"
        tag:  "application"
        url:  "https://ytdl.drak3.io"

      - name: "VS Code"
        icon: "fas fa-code"
        subtitle: "https://code.drak3.io"
        tag:  "application"
        url:  "https://code.drak3.io"

      - name: "Whoogle"
        icon: "fab fa-google"
        subtitle: "https://google.drak3.io"
        tag:  "application"
        url:  "https://google.drak3.io"

      - name: "HandBrake"
        logo: "assets/HandBrake_Icon.png"
        subtitle: "https://hb.drak3.io"
        tag:  "application"
        url:  "https://hb.drak3.io"

      - name: "Guacamole"
        logo: "assets/guacamole-logo.png"
        subtitle: "https://guac.drak3.io"
        tag:  "application"
        url:  "https://guac.drak3.io"

  - name: "GitHub"
    icon: "fab fa-github"
    items:
    
      - name: "Scripts"
        icon: "fab fa-github"
        subtitle: "Scripts Git Repo"
        tag:  "GitHub"
        url:  "https://github.com/educatedCaveman/scripts"
    
      - name: "Dotfiles"
        icon: "fab fa-github"
        subtitle: "Dotfiles Git Repo"
        tag:  "GitHub"
        url:  "https://github.com/educatedCaveman/dotfiles"
    
      - name: "Ansible"
        icon: "fab fa-github"
        subtitle: "Ansible Git Repo"
        tag:  "GitHub"
        url:  "https://github.com/educatedCaveman/ansible"
    
      - name: "Docker"
        icon: "fab fa-github"
        subtitle: "Docker Git Repo"
        tag:  "GitHub"
        url:  "https://github.com/educatedCaveman/docker-lab"
    
      - name: "Jenkins"
        icon: "fab fa-github"
        subtitle: "Jenkins Git Repo"
        tag:  "GitHub"
        url:  "https://github.com/educatedCaveman/Jenkins"