## Configuration
---
title: "Grand Ol' Dungeon of the Horned God"
subtitle: "Homer"
# documentTitle: "Welcome" # Customize the browser tab text
logo: "assets/icons/icon-maskable.png"
# https://fontawesome.com/v4.7.0/icons/
# Alternatively a fa icon can be provided:
# icon: "fas fa-skull-crossbones"

header: true # Set to false to hide the header
footer: false # set false if you want to hide it.

# TODO: try setting this to 4
# columns: "auto" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
columns: 4
connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example)

# Optional theming
theme: default # 'default' or one of the themes available in 'src/assets/themes'.

#default colors from github:
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
    background-image: "assets/your/light/bg.png"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"
    background-image: "assets/your/dark/bg.png"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/educatedCaveman"
    target: "_blank" # optional html tag target attribute
  - name: "Font Awesome Icons"
    icon: "fab fa-font-awesome"
    url:  "https://fontawesome.com/v4.7.0/icons/"

services:
  - name: "Servers"
    icon: "fas fa-server"
    items:
      - name: "Mobius"
        logo: "assets/TrueNAS-Core.png"
        url:  "https://mobius.drak3.io"

      - name: "Tesseract"
        logo: "assets/Proxmox-logo.png"
        url:  "https://tesseract.drak3.io"

      - name: "Unifi Controller"
        logo: "assets/unifi_logo.png"
        url:  "https://unifi.drak3.io"

      - name: "Unifi Protect"
        logo: "assets/unifi_logo.png"
        url:  "https://nvr.drak3.io"

      - name: "Guacamole"
        logo: "assets/guacamole-logo.png"
        url:  "https://guac.drak3.io"

      - name: "Mobius (iDRAC)"
        logo: "assets/dell_logo.png"
        url:  "https://idrac.mobius.drak3.io"

      - name: "Tesseract (iDRAC)"
        logo: "assets/dell_logo.png"
        url:  "https://idrac.tesseract.drak3.io"

      - name: "pfSense (IPMI)"
        icon: "fas fa-server"
        url:  "http://192.168.1.10"

      - name: "OctoPrint"
        logo: "assets/octoprint.png"
        url:  "https://octopi.drak3.io"

  - name: "Media Services"
    icon: "fas fa-server"
    items:

      - name: "Plex"
        logo: "assets/plex.svg"
        url:  "https://plex.drak3.io"

      - name: "Ombi"
        logo: "assets/ombi_icon.png"
        url:  "https://ombi.drak3.io"

      - name: "Tautulli"
        logo: "assets/tautulli.png"
        url:  "https://tau.drak3.io/"

      - name: "NextCloud"
        logo: "assets/Nextcloud_Logo.svg"
        url:  "https://cloud.drak3.io"

      - name: "Whoogle"
        icon: "fab fa-google"
        url:  "https://google.drak3.io"

      - name: "MineOS"
        logo: "assets/minecraft.png"
        url:  "https://mineos.drak3.io"

      - name: "qBittorrent"
        logo: "assets/qbittorrent.png"
        url:  "https://qbt.drak3.io/"

      - name: "HandBrake"
        logo: "assets/HandBrake_Icon.png"
        url:  "https://hb.drak3.io"

      - name: "YouTube DL"
        icon: "fab fa-youtube"
        url:  "https://ytdl.drak3.io"

  - name: "Data Services"
    icon: "fas fa-server"
    items:

      - name: "Syncthing"
        logo: "assets/syncthing.png"
        url:  "https://sync.drak3.io/syncthing/"

      - name: "Minio"
        logo: "assets/minio.jpg"
        url:  "https://s3.drak3.io/"

      - name: "InfluxDB / Chronograf"
        logo: "assets/influxdata-logo.svg"
        url:  "https://influx.drak3.io/"

      - name: "Grafana"
        logo: "assets/grafana.png"
        url:  "https://grafana.drak3.io/"

      - name: "Graylog"
        logo: "assets/graylog-icon.svg"
        url:  "http://graylog.vm:9000"

      - name: "Unifi Protect (feeds)"
        logo: "assets/unifi_logo.png"
        url:  "http://192.168.200.2"

  - name: "Development Tools"
    icon: "fas fa-server"
    items:

      - name: "Jenkins"
        logo: "assets/jenkins.svg"
        url:  "https://jenkins.drak3.io/"

      - name: "Gitea"
        logo: "assets/Gitea_Logo.svg"
        url:  "https://git.drak3.io/"

      - name: "VS Code"
        icon: "fas fa-code"
        url:  "https://code.drak3.io"

      - name: "Portainer"
        logo: "assets/docker.png"
        url:  "https://portainer.drak3.io/"

  - name: "Admin Tools"
    icon: "fas fa-server"
    items:

      - name: "Apt Cache NG"
        icon: "fas fa-cubes"
        url:  "https://apt-cache.drak3.io/acng-report.html"

      - name: "Apt Mirror"
        icon: "fas fa-database"
        url:  "https://apt-mirror.drak3.io/ubuntu"

      - name: "Singularity"
        logo: "assets/Pi-hole_vector_logo.svg.png"
        url:  "https://pihole.drak3.io/admin/index.php"

      - name: "Event Horizon"
        logo: "assets/Pi-hole_vector_logo.svg.png"
        url:  "https://pihole2.drak3.io/admin/index.php"

  - name: "GitHub"
    icon: "fab fa-github"
    items:
    
      - name: "Scripts"
        icon: "fab fa-github"
        url:  "https://github.com/educatedCaveman/scripts"
    
      - name: "Dotfiles"
        icon: "fab fa-github"
        url:  "https://github.com/educatedCaveman/dotfiles"
    
      - name: "Ansible"
        icon: "fab fa-github"
        url:  "https://github.com/educatedCaveman/ansible"
    
      - name: "Docker"
        icon: "fab fa-github"
        url:  "https://github.com/educatedCaveman/docker-lab"
    
      - name: "Jenkins"
        icon: "fab fa-github"
        url:  "https://github.com/educatedCaveman/Jenkins"
    
      - name: "Documentation"
        icon: "fab fa-github"
        url:  "https://github.com/educatedCaveman/Jenkins"

  - name: "Netdata"
    icon: "fas fa-tachometer"
    items:
    
      - name: "Tesseract"
        logo: "assets/netdata_pve.svg"
        url:  "https://tesseract.srv:19999"
    
      - name: "Nextcloud"
        logo: "assets/netdata_logo.svg"
        url:  "https://nextcloud.vm:19999"
    
      - name: "Moria"
        logo: "assets/netdata_logo.svg"
        url:  "https://moria.vm:19999"
    
      - name: "GitLab"
        logo: "assets/netdata_logo.svg"
        url:  "https://gitlab.vm:19999"
    
      - name: "APT Mirror"
        logo: "assets/netdata_logo.svg"
        url:  "https://apt-mirror.vm:19999"
    
      - name: "APT Cache"
        logo: "assets/netdata_logo.svg"
        url:  "https://apt-cache.vm:19999"
    
      - name: "Plex"
        logo: "assets/netdata_logo.svg"
        url:  "https://plex.vm:19999"
    
      - name: "Singularity"
        logo: "assets/netdata_logo.svg"
        url:  "https://singularity.vm:19999"
    
      - name: "Jenkins"
        logo: "assets/netdata_logo.svg"
        url:  "https://jenkins.lab:19999"
    
      - name: "Swarm API LB (PRD)"
        logo: "assets/netdata_logo.svg"
        url:  "https://swarm-api-lb.vm:19999"
    
      - name: "Swarm Manager 1 (PRD)"
        logo: "assets/netdata_logo.svg"
        url:  "https://sevastopol-manager-01.vm:19999"
    
      - name: "Swarm Manager 2 (PRD)"
        logo: "assets/netdata_logo.svg"
        url:  "https://sevastopol-manager-02.vm:19999"
    
      - name: "Swarm Manager 3 (PRD)"
        logo: "assets/netdata_logo.svg"
        url:  "https://sevastopol-manager-03.vm:19999"
    
      - name: "Swarm Worker 1 (PRD)"
        logo: "assets/netdata_logo.svg"
        url:  "https://sevastopol-worker-01.vm:19999"
    
      - name: "Swarm Worker 2 (PRD)"
        logo: "assets/netdata_logo.svg"
        url:  "https://sevastopol-worker-02.vm:19999"
    
      - name: "Swarm Worker 3 (PRD)"
        logo: "assets/netdata_logo.svg"
        url:  "https://sevastopol-worker-03.vm:19999"
    
      - name: "Swarm Worker 4 (PRD)"
        logo: "assets/netdata_logo.svg"
        url:  "https://sevastopol-worker-04.vm:19999"
    
      - name: "Swarm API LB (DEV)"
        logo: "assets/netdata_logo.svg"
        url:  "https://swarm-api-lb.lab:19999"
    
      - name: "Swarm Manager 1 (DEV)"
        logo: "assets/netdata_logo.svg"
        url:  "https://lv426-manager-01.lab:19999"
    
      - name: "Swarm Manager 2 (DEV)"
        logo: "assets/netdata_logo.svg"
        url:  "https://lv426-manager-02.lab:19999"
    
      - name: "Swarm Manager 3 (DEV)"
        logo: "assets/netdata_logo.svg"
        url:  "https://lv426-manager-03.lab:19999"
    
      - name: "Swarm Worker 1 (DEV)"
        logo: "assets/netdata_logo.svg"
        url:  "https://lv426-worker-01.lab:19999"
    
      - name: "Swarm Worker 2 (DEV)"
        logo: "assets/netdata_logo.svg"
        url:  "https://lv426-worker-02.lab:19999"
    
      - name: "Swarm Worker 3 (DEV)"
        logo: "assets/netdata_logo.svg"
        url:  "https://lv426-worker-03.lab:19999"
    
      - name: "Swarm Worker 4 (DEV)"
        logo: "assets/netdata_logo.svg"
        url:  "https://lv426-worker-04.lab:19999"
    
      - name: "Event Horizon"
        logo: "assets/netdata_pve.svg"
        url:  "https://event-horizon.srv:19999"
    
      - name: "Dilithium"
        logo: "assets/netdata_pve.svg"
        url:  "https://dilithium.srv:19999"

  - name: "DEV"
    icon: "fas fa-server"
    items:

      - name: "Guacamole (DEV)"
        logo: "assets/guacamole-logo.png"
        url:  "https://guac.dev.drak3.io"

      - name: "HandBrake"
        logo: "assets/HandBrake_Icon.png"
        url:  "https://hb.dev.drak3.io"

      - name: "YouTube DL (DEV)"
        icon: "fab fa-youtube"
        url:  "https://ytdl.dev.drak3.io"

      - name: "Ombi"
        logo: "assets/ombi_icon.png"
        url:  "https://ombi.dev.drak3.io"

      - name: "Tautulli"
        logo: "assets/tautulli.png"
        url:  "https://tau.dev.drak3.io/"

      - name: "VS Code (DEV)"
        icon: "fas fa-code"
        url:  "https://code.dev.drak3.io"

      - name: "Portainer (DEV)"
        logo: "assets/docker.png"
        url:  "https://portainer.dev.drak3.io/"
        