---
version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/mobius/docker/watchtower/slack_webhook.env:/etc/slack_webhook.env
    environment:
     - WATCHTOWER_NOTIFICATIONS=slack
     - WATCHTOWER_NOTIFICATIONS_LEVEL=info
     - WATCHTOWER_NOTIFICATION_SLACK_CHANNEL=#notifications
     - WATCHTOWER_CLEANUP=true
     - WATCHTOWER_ROLLING_RESTART=true
     - WATCH_TEST=${/etc/slack_webhook.env}
    restart: unless-stopped
    network_mode: "bridge"