---
version: "2.4"
services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - PASSWORD=password #optional
      - SUDO_PASSWORD=password #optional
      #- PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - /mnt/mobius/docker/code-server/config:/config:Z
    ports:
      - 9443:8443
    restart: unless-stopped
