---
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - WATCHTOWER_NOTIFICATIONS=slack
     - WATCHTOWER_NOTIFICATIONS_LEVEL=info
     - WATCHTOWER_NOTIFICATION_SLACK_CHANNEL=#notifications
     - WATCHTOWER_CLEANUP=true
     - WATCHTOWER_ROLLING_RESTART=true
     - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=/var/run/SLACK_WEBHOOK_WATCHTOWER
    restart: unless-stopped
    network_mode: "bridge"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    secrets:
      SLACK_WEBHOOK_WATCHTOWER:
        external: true

Watchtower:
	containrrr/watchtower

volumes:
	/var/run/docker.sock	/var/run/docker.sock

environment variables:
	WATCHTOWER_NOTIFICATIONS				        slack
	WATCHTOWER_NOTIFICATIONS_LEVEL          info
	WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL  /run/secrets/SLACK_WEBHOOK_WATCHTOWER
	WATCHTOWER_NOTIFICATION_SLACK_CHANNEL   #notifications
	WATCHTOWER_CLEANUP						          true
	WATCHTOWER_ROLLING_RESTART				      true
	TZ										                  America/New_York

other:  
    restart: unless-stopped
    network_mode: "bridge"