#homer docker compose
---
version: '3'
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /mnt/mobius/docker/homer/assets/:/www/assets
    ports:
      - 8080:8080
    environment:
     - UID=1000
     - GID=1000
    restart: unless-stopped
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
