---
# this comment is a hack - as is this
version: '3'
services:
  ytdl_material:
    environment:
      ALLOW_CONFIG_MUTATIONS: "true"
    restart: always
    volumes:
      - /docker/docker-lab/ytdl/appdata:/app/appdata
      - /docker/docker-lab/ytdl/audio:/app/audio
      - /docker/docker-lab/ytdl/video:/app/video
      - /docker/docker-lab/ytdl/subscriptions:/app/subscriptions
    ports:
      - "8998:17442"
    image: tzahi12345/youtubedl-material:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]