---
version: "2.4"
services:
  ytdl_material:
    environment:
      ALLOW_CONFIG_MUTATIONS: "true"
    restart: always
    volumes:
      - /mnt/mobius/docker/ytdl/appdata:/app/appdata
      - /mnt/mobius/staging/ytdl/audio:/app/audio
      - /mnt/mobius/staging/ytdl/video:/app/video
      - /mnt/mobius/docker/ytdl/subscriptions:/app/subscriptions
    ports:
      - "8998:17442"
    image: tzahi12345/youtubedl-material:latest
